---
- name: Install Admin Tools
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - unzip
    - psmisc
    - mlocate
    - telnet
    - lrzsz
    - vim
    - elinks-lite
    - rcconf
    - htop
    - sudo
    - p7zip
    - dos2unix
    - curl

- name: Install git
  apt: name=git-core state=latest

- name: Install Exim4
  apt: name={{item}} state=latest
  with_items:
    - exim4-config
    - exim4-daemon-light

- name: Install python libs
  apt: name={{item}} state=latest
  with_items:
    - libgeos-c1
    - python-dev
    - python-lxml
    - python-setuptools
    - python-dateutil
    - python-serial
    - python-imaging
    - python-reportlab
    - python-matplotlib
    - python-xlwt
    - build-essential
    - libgeos-dev
    - python-pip

- name: Install Shapely
  pip: name=Shapely

- name: Install XLRD
  pip: name=xlrd

- name: Create web2py user
  #user: name=web2py system=true
  command: adduser --system --disabled-password web2py

- name: Create web2py group
  group: name=web2py state=present

- name: Create symlink
  file: src=/home/web2py dest=/home/prod state=link owner=web2py group=web2py
  when: type == 'prod'

- name: Clone web2py
  git: repo=git://github.com/web2py/web2py.git dest=/home/{{ type}}
  when: type != 'prod' or inventory_hostname != '127.0.0.1'
  tags:
    - test
    - demo

- name: Copy wsgihandler
  command: cp -f /home/{{ type }}/handlers/wsgihandler.py /home/{{ type }}
  tags:
    - test
    - demo

- name: Copy routes.py
  copy: src=routes.py dest=/home/{{ type }}/routes.py
  tags:
    - test
    - demo

- name: Create matplotlib directory
  file: path=/home/{{ type }}/.matplotlib state=directory owner=web2py
  tags:
    - test
    - demo

- name: Update wsgihandler.py
  lineinfile: dest=/home/{{ type }}/wsgihandler.py
              regexp=''
              insertafter=EOF
              line='os.environ["MPLCONFIGDIR"] = "/home/{{ type }}/.matplotlib"'
  tags:
    - test
    - demo

# - name: Edit matplotlibrc
#   lineinfile: dest=/etc/matplotlibrc state=present backref=yes regexp='backend      : TkAgg' line='backend      : Agg'

- name: Clone Eden
  git: repo=git://github.com/flavour/eden.git dest=/home/{{ type }}/applications/eden
  tags:
    - test
    - demo

- name: Fix permissions
  file: path=/home/{{item}} state=directory owner=web2py
  with_items:
    - "{{ type }}"
    - "{{ type }}/applications"
    - "{{ type }}/applications/admin/cache"
    - "{{ type }}/applications/admin/cron"
    - "{{ type }}/applications/admin/databases"
    - "{{ type }}/applications/admin/errors"
    - "{{ type }}/applications/admin/sessions"
    - "{{ type }}/applications/eden"
    - "{{ type }}/applications/eden/cache"
    - "{{ type }}/applications/eden/cron"
    - "{{ type }}/applications/eden/databases"
    - "{{ type }}/applications/eden/errors"
    - "{{ type }}/applications/eden/models"
    - "{{ type }}/applications/eden/sessions"
    - "{{ type }}/applications/eden/static/img/markers"
    - "{{ type }}/applications/eden/static/cache"
    - "{{ type }}/applications/eden/static/cache/chart"
    - "{{ type }}/applications/eden/uploads"
    - "{{ type }}/applications/eden/uploads/gis_cache"
    - "{{ type }}/applications/eden/uploads/images"
    - "{{ type }}/applications/eden/uploads/tracks"
  tags:
    - test
    - demo
